# Generated by Django 5.1.3 on 2024-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0002_category_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Cateogry', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Nationality', 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='exit', upload_to='cover_images/'),
            preserve_default=False,
        ),
    ]
