# Generated by Django 5.1.3 on 2024-12-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0003_alter_category_options_alter_nationality_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='cover_image',
        ),
    ]
