# Generated by Django 5.1.3 on 2024-12-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0004_rename_image_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='date_establishment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
