# Generated by Django 5.1.3 on 2024-12-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0005_publisher_date_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='exit', upload_to='category_images/'),
            preserve_default=False,
        ),
    ]
