# Generated by Django 5.1.3 on 2024-12-27 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0006_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
