# Generated by Django 5.1.3 on 2024-12-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='exit', max_length=120),
            preserve_default=False,
        ),
    ]
