# Generated by Django 5.1.3 on 2024-12-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_post_slug'),
        ('home', '0002_tag_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='home.tag'),
        ),
    ]
