# Generated by Django 5.1.3 on 2024-12-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_gender_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
