# Generated by Django 5.1.3 on 2024-12-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('literature', '0005_publisher_date_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='cblogs', to='literature.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default='exit', upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
