# Generated by Django 5.1.3 on 2024-12-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_like_parent_content_type_like_parent_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='parent_object_id',
        ),
    ]
